import 'product.dart';

class Myproducts {
  static List<Product> allProducts = [
    Product(
      id: 1,
      name: "Under Armour Project Rock 4",
      category: "Tenis Deportivos",
      image: "assets/sneakers/1.jpg",
      description:
          "Zapatillas de entrenamiento diseñadas en colaboración con Dwayne 'The Rock' Johnson.",
      price: 149.99,
      quantity: 18,
    ),
    Product(
      id: 2,
      name: "Nike Air Zoom Vapor X",
      category: "Tenis Deportivos",
      image: "assets/sneakers/2.jpg",
      description: "Zapatillas de tenis diseñadas para velocidad y comodidad.",
      price: 129.99,
      quantity: 15,
    ),
    Product(
      id: 3,
      name: "Adidas Barricade Club",
      category: "Tenis Deportivos",
      image: "assets/sneakers/3.jpg",
      description:
          "Zapatillas de tenis duraderas con excelente soporte y tracción.",
      price: 89.99,
      quantity: 25,
    ),
    Product(
      id: 4,
      name: "Head Revolt Pro 3.0",
      category: "Tenis Deportivos",
      image: "assets/sneakers/4.jpg",
      description: "Zapatillas para jugadores agresivos con alta estabilidad.",
      price: 159.99,
      quantity: 18,
    ),
    Product(
      id: 5,
      name: "Asics Gel-Resolution 8",
      category: "Tenis Deportivos",
      image: "assets/sneakers/5.jpg",
      description:
          "Zapatillas de tenis con amortiguación y soporte para largos partidos.",
      price: 139.99,
      quantity: 22,
    ),
    Product(
      id: 6,
      name: "New Balance 996",
      category: "Tenis Deportivos",
      image: "assets/sneakers/6.jpg",
      description: "Zapatillas de tenis con estilo clásico y comodidad.",
      price: 109.99,
      quantity: 30,
    ),
    Product(
      id: 7,
      name: "Puma Court Star",
      category: "Tenis Deportivos",
      image: "assets/sneakers/7.jpg",
      description: "Zapatillas de tenis con diseño retro y versatilidad.",
      price: 79.99,
      quantity: 12,
    ),
    Product(
      id: 8,
      name: "Mizuno Wave Exceed Tour 4",
      category: "Tenis Deportivos",
      image: "assets/sneakers/8.jpg",
      description: "Zapatillas de tenis para movimientos rápidos en la cancha.",
      price: 129.99,
      quantity: 17,
    ),
    Product(
      id: 9,
      name: "Under Armour HOVR Sonic",
      category: "Tenis Deportivos",
      image: "assets/sneakers/9.jpg",
      description:
          "Zapatillas de tenis con tecnología de amortiguación y soporte.",
      price: 109.99,
      quantity: 19,
    ),
    Product(
      id: 10,
      name: "Reebok Nano X1",
      category: "Tenis Deportivos",
      image: "assets/sneakers/10.jpg",
      description: "Zapatillas versátiles para entrenamientos de crossfit.",
      price: 119.99,
      quantity: 14,
    ),
    Product(
      id: 11,
      name: "Fila Axilus 2 Energized",
      category: "Tenis Deportivos",
      image: "assets/sneakers/11.jpg",
      description: "Zapatillas de tenis con un diseño moderno y comodidad.",
      price: 99.99,
      quantity: 21,
    ),
    Product(
      id: 12,
      name: "Yonex Eclipsion 2",
      category: "Tenis Deportivos",
      image: "assets/sneakers/12.jpg",
      description:
          "Zapatillas de tenis de alta calidad con excelente estabilidad.",
      price: 149.99,
      quantity: 16,
    ),
    Product(
      id: 13,
      name: "Babolat Propulse Fury",
      category: "Tenis Deportivos",
      image: "assets/sneakers/13.jpg",
      description: "Zapatillas de tenis para jugadores agresivos en la cancha.",
      price: 139.99,
      quantity: 20,
    ),
    Product(
      id: 14,
      name: "Salomon Speedcross 5",
      category: "Tenis de Trail",
      image: "assets/sneakers/14.jpg",
      description:
          "Zapatillas para correr en terrenos accidentados y senderos.",
      price: 129.99,
      quantity: 24,
    ),
    Product(
      id: 15,
      name: "Adidas Ultraboost",
      category: "Zapatillas para Correr",
      image: "assets/sneakers/15.jpg",
      description: "Zapatillas de running con amortiguación y comodidad.",
      price: 169.99,
      quantity: 28,
    ),
    Product(
      id: 16,
      name: "Mizuno Wave Rider 24",
      category: "Zapatillas para Correr",
      image: "assets/sneakers/16.jpg",
      description: "Zapatillas de running con excelente absorción de impactos.",
      price: 139.99,
      quantity: 23,
    ),
    Product(
      id: 17,
      name: "Nike React Infinity Run",
      category: "Zapatillas para Correr",
      image: "assets/sneakers/17.jpg",
      description: "Zapatillas de running diseñadas para prevenir lesiones.",
      price: 179.99,
      quantity: 26,
    ),
    Product(
      id: 18,
      name: "Asics Gel-Nimbus 23",
      category: "Zapatillas para Correr",
      image: "assets/sneakers/18.jpg",
      description: "Zapatillas de running con un alto nivel de amortiguación.",
      price: 159.99,
      quantity: 22,
    ),
    //Jackets
    Product(
      id: 19,
      name: "Wilson Pro Staff RF97 Autograph",
      category: "Chamarra",
      image: "assets/jackets/1.jpg",
      description:
          "Diseñada para Roger Federer, esta chamarra ofrece calidad y precio.",
      price: 1329.99,
      quantity: 20,
    ),
    Product(
      id: 20,
      name: "Nike Sportswear Windrunner",
      category: "Chamarra",
      image: "assets/jackets/2.jpg",
      description:
          "Chamarra deportiva con estilo clásico y protección contra el viento.",
      price: 89.99,
      quantity: 15,
    ),
    Product(
      id: 21,
      name: "Adidas Essential Tricot Track Jacket",
      category: "Chamarra",
      image: "assets/jackets/3.jpg",
      description:
          "Chamarra deportiva de tricot con un diseño versátil y comodidad.",
      price: 69.99,
      quantity: 25,
    ),
    Product(
      id: 22,
      name: "Puma T7 Vintage Track Jacket",
      category: "Chamarra",
      image: "assets/jackets/4.jpg",
      description: "Chamarra deportiva retro con un toque de estilo.",
      price: 79.99,
      quantity: 18,
    ),
    Product(
      id: 23,
      name: "Columbia Watertight II Jacket",
      category: "Chamarra",
      image: "assets/jackets/5.jpg",
      description: "Chamarra impermeable ideal para actividades al aire libre.",
      price: 99.99,
      quantity: 22,
    ),
    Product(
      id: 24,
      name: "The North Face Apex Bionic 2 Jacket",
      category: "Chamarra",
      image: "assets/jackets/6.jpg",
      description:
          "Chamarra resistente al viento y ligera para actividades al aire libre.",
      price: 149.99,
      quantity: 30,
    ),
    Product(
      id: 25,
      name: "Under Armour Rival Fleece Hoodie",
      category: "Chamarra",
      image: "assets/jackets/7.jpg",
      description: "Sudadera con capucha para mantenerse abrigado y cómodo.",
      price: 69.99,
      quantity: 12,
    ),
    Product(
      id: 26,
      name: "New Balance Windcheater Jacket",
      category: "Chamarra",
      image: "assets/jackets/8.jpg",
      description:
          "Chamarra deportiva con protección contra el viento y estilo moderno.",
      price: 79.99,
      quantity: 17,
    ),
    Product(
      id: 27,
      name: "Reebok Active Enhanced Track Jacket",
      category: "Chamarra",
      image: "assets/jackets/9.jpg",
      description:
          "Chamarra de entrenamiento con diseño funcional y durabilidad.",
      price: 59.99,
      quantity: 19,
    ),
    Product(
      id: 28,
      name: "Adidas Tiro 19 Training Jacket",
      category: "Chamarra",
      image: "assets/jackets/10.jpg",
      description:
          "Chamarra de entrenamiento con tejido transpirable y comodidad.",
      price: 79.99,
      quantity: 15,
    ),
    Product(
      id: 29,
      name: "Nike Sportswear Tech Fleece Windrunner",
      category: "Chamarra",
      image: "assets/jackets/11.jpg",
      description:
          "Chamarra deportiva con tecnología Tech Fleece para abrigar sin peso adicional.",
      price: 129.99,
      quantity: 20,
    ),
    Product(
      id: 30,
      name: "Under Armour Storm Launch Jacket",
      category: "Chamarra",
      image: "assets/jackets/12.jpg",
      description: "Chamarra ligera y repelente al agua para corredores.",
      price: 99.99,
      quantity: 18,
    ),
    Product(
      id: 31,
      name: "Columbia Steens Mountain",
      category: "Chamarra",
      image: "assets/jackets/13.jpg",
      description:
          "Chamarra de forro polar para mantenerse abrigado en climas fríos.",
      price: 69.99,
      quantity: 25,
    ),
    Product(
      id: 32,
      name: "The North Face Denali 2 Jacket",
      category: "Chamarra",
      image: "assets/jackets/14.jpg",
      description:
          "Chamarra de forro polar versátil y duradera para actividades al aire libre.",
      price: 159.99,
      quantity: 22,
    ),
    Product(
      id: 33,
      name: "Puma Evostripe Proknit Jacket",
      category: "Chamarra",
      image: "assets/jackets/15.jpg",
      description:
          "Chamarra deportiva con tejido Proknit para comodidad y estilo.",
      price: 79.99,
      quantity: 17,
    ),
    Product(
      id: 34,
      name: "New Balance Core Softshell Jacket",
      category: "Chamarra",
      image: "assets/jackets/16.jpg",
      description:
          "Chamarra softshell resistente al viento y al agua para actividades al aire libre.",
      price: 89.99,
      quantity: 16,
    ),
    Product(
      id: 35,
      name: "Reebok Workout Ready Track Jacket",
      category: "Chamarra",
      image: "assets/jackets/17.jpg",
      description: "Chamarra de entrenamiento con estilo clásico y comodidad.",
      price: 69.99,
      quantity: 14,
    ),
    Product(
      id: 36,
      name: "Adidas Alphaskin Sport Fitted Jacket",
      category: "Chamarra",
      image: "assets/jackets/18.jpg",
      description:
          "Chamarra deportiva ajustada para actividades de alta intensidad.",
      price: 79.99,
      quantity: 19,
    ),
  ];
}
